openapi: 3.0.3
info:
  title: Petstore API (JSON Server)
  description: A fake REST API for fetching pets using json-server.
  version: 1.0.0
servers:
  - url: https://{environment}/v1
    variables:
      environment:
        default: api.dev
        enum:
          - api.dev
          - api.staging
          - api.prod
paths:
  /pets:
    get:
      summary: Get all pets
      description: Returns a list of pets from the store.
      responses:
        "200":
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Buddy
        type:
          type: string
          example: dog
        age:
          type: integer
          example: 3
