/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Petstore API (JSON Server)
 * A fake REST API for fetching pets using json-server.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Pet {
  id?: number;
  name?: string;
  type?: string;
  age?: number;
}

/**
 * Returns a list of pets from the store.
 * @summary Get all pets
 */
export const getPets = <TData = AxiosResponse<Pet[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:4000/pets`,options
    );
  }

export type GetPetsResult = AxiosResponse<Pet[]>
